version: '3.8'

services:
  flask:
    image: flask
    build: ./app
    command: python wsgi.py runserver 0.0.0.0:8000
    context: .
    volumes:
      - ./app/:/usr/src/app/
    dockerfile: ./Dockerfile
    ports:
      - 5000:5000
